### ISSUE TITLE
Potential Related Work

### ISSUE THREAD

**Issue by Samyu0304** [BUPT-GAMMA/GFMPapers#1]
Dear Authors,

Thanks for this awesome repo! We would like to introduce a related work on using the graph structure of general tasks to enhance complex reasoning with LLMs "Thought Propagation: An Analogical Approach to Complex Reasoning with Large Language Models". We hope our suggestion could enrich this awesome paper list ☺️ !

Best,
Junchi Yu

**Comment by J-cabin** [comment]
Thank you for your suggestion. We have noted that this paper uses graph learning techniques to improve the performance of LLMs in reasoning-related tasks (mainly natural language understanding and generation). Although, by definition, this does not fall within the category of graph foundation models, we have included it as relevant work in our paper list.

**Comment by bobobe** [comment]
Thanks，I'll reply you soon
